// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PartsTrackerApi.Infrastructure;

#nullable disable

namespace PartsTrackerApi.Migrations
{
    [DbContext(typeof(PartsDbContext))]
    [Migration("20250705104723_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PartsTrackerApi.Data.Part", b =>
                {
                    b.Property<string>("PartNumber")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastStockTake")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LocationCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuantityOnHand")
                        .HasColumnType("integer");

                    b.HasKey("PartNumber");

                    b.ToTable("Parts");

                    b.HasData(
                        new
                        {
                            PartNumber = "MB1001",
                            Description = "Bolt",
                            LastStockTake = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LocationCode = "FP1",
                            QuantityOnHand = 60
                        },
                        new
                        {
                            PartNumber = "MB1002",
                            Description = "Nut",
                            LastStockTake = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LocationCode = "FP2",
                            QuantityOnHand = 100
                        },
                        new
                        {
                            PartNumber = "MB1003",
                            Description = "Washer",
                            LastStockTake = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LocationCode = "FP2",
                            QuantityOnHand = 75
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
