services:
  
  partstrackerapi:
      image: partstrackerapi
      build:
        context: .
        dockerfile: PartsTrackerAPI.dockerfile
      ports:
        - "5000:8080"
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ConnectionStrings__DefaultConnection=Host=postgres;Database=PartsDb;Username=postgres;Password=postgres123
      depends_on:
        - postgres
      restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: parts_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: PartsDb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:

