#services:
#  partstrackerapi:
#    image: partstrackerapi
#    build:
#      context: .
#      dockerfile: PartsTrackerApi/Dockerfile
services:
  postgres:
    image: postgres:16
    container_name: parts_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: PartsDb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:

